In [112]:
import pandas as pd

In [113]:
rows = [["apple"], ["banana"]]
df_products = pd.DataFrame(rows, columns = ["products"])
df_products

  products
0    apple
1   banana

In [114]:
df_products = pd.DataFrame({"product": ["apple", "banana"], "price": [1.20, 0.80]})
df_products

  product  price
0   apple    1.2
1  banana    0.8

In [115]:
df_store = pd.DataFrame({"item": ["bread", "milk"], "quantity": [5, 10]})

In [116]:
df_store

    item  quantity
0  bread         5
1   milk        10

In [117]:
df_store.head(1)

    item  quantity
0  bread         5

In [118]:
df_store.head(2)

    item  quantity
0  bread         5
1   milk        10

In [119]:
df_store.shape

(2, 2)

In [120]:
df_store.dtypes

item          str
quantity    int64
dtype: object

In [121]:
df_store.describe()

        quantity
count   2.000000
mean    7.500000
std     3.535534
min     5.000000
25%     6.250000
50%     7.500000
75%     8.750000
max    10.000000

In [122]:
df_store.max()

item        milk
quantity      10
dtype: object

In [ ]:
df_store.min()

In [ ]:
df_store["item"]

### Pandas Quick Reference

    Q: What is the standard command for importing the Pandas library in Python?
        import pandas as pd
    
    Q: What is the one-dimensional data structure in Pandas that represents a single column of data called?
        Series
    
    Q: Which method is used to quickly preview only the first few rows of a DataFrame?
        .head()
    
    Q: Which attribute is used to check the total number of rows and columns in a table?
        .shape
    
    Q: If you have a DataFrame called 'dfStore' and want to see statistical data such as mean and maximum for numeric columns, which command will you use?
        dfStore.describe()

In [ ]:
data_col = {"a": [4, 5, 6], "b": [7, 8, 9]} 
df = pd.DataFrame(data_col)
print(df)

In [ ]:
data_row = [[4, 7, 10], [5, 8, 11], [6, 9, 12]] 
df = pd.DataFrame(data_row, columns=['a', 'b', 'c']) 
print(df)

* Q: What is the main difference between Series and DataFrame objects in Pandas?
    - Number of dimensions

* Q: What does the dtypes attribute of a DataFrame object contain?
    - The data types of the columns

* Q: How are specific rows identified in Pandas for quick access to information?
    - Through unique indexes

In [ ]:
pd.Series([10, 20]).index

In [ ]:
pd.Series([10, 20]).sum()

* What is the result of pd.Series([10, 20]).index if you do not pass an index argument? 
    - RangeIndex(0, 2)
* Which Pandas property tells you that each column in a DataFrame has one data type?
    - dtypes
* What is the main difference between Series and a NumPy array for accessing data?
    - You use labels
* What is the fastest way to see the size (rows and columns) of a DataFrame? 
    - df.shape
* Why does each column in Pandas have only one data type (dtype)? 
    - For faster work
* Why is Pandas often faster than Python lists for large tables? 
    - Vectorized operations
* How does Pandas treat empty cells in a table? 
    - NaN values
* Why do people use a DataFrame instead of nested lists for big data? 
    - Vectorized operations

In [ ]:
df_fruits = pd.DataFrame({"price": [1.20, 1.50, 1.90]}, index = ["apple", "banana", "orange"])

In [ ]:
df_fruits = pd.DataFrame({"Fruit":  ["apple", "banana", "orange"], "Price": [1.20, 1.50, 1.90]})

In [ ]:
df_fruits["Fruit"]

0     apple
1    banana
2    orange
Name: Fruit, dtype: str

In [ ]:
df_fruits[["Fruit"]]

    Fruit
0   apple
1  banana
2  orange

In [ ]:
df_fruits["Fruit"].dtypes

In [ ]:
df_fruits[["Fruit"]].dtypes

Fruit    str
dtype: object

* When you write df_fruits["Fruit"], you tell Pandas: "Give me only this column." Pandas pulls the column from the table and returns it as a Series (one dimension).
* When you write df_fruits[["Fruit"]], you say: "Give me a small table (subset) with these columns."
Because you asked for a table (the list inside double brackets), Pandas returns a DataFrame (two dimensions), even if there is only one column.

In [ ]:
df_fruits[["Fruit", "Price"]]

    Fruit  Price
0   apple    1.2
1  banana    1.5
2  orange    1.9

In [ ]:
df_fruits["Fruit", "Price"]

KeyError: ('Fruit', 'Price')

In [ ]:
data = { 'Store': ['Sofia', 'Plovdiv', 'Varna'], 'Sales': [12000, 8500, 9200], 'Inventory': [450, 310, 520] } 
df_shops = pd.DataFrame(data)

In [ ]:
df_shops["Sales"]

0    12000
1     8500
2     9200
Name: Sales, dtype: int64

In [ ]:
df_shops[["Sales"]]

   Sales
0  12000
1   8500
2   9200

In [ ]:
df_shops["Sales"].dtypes

dtype('int64')

In [ ]:
df_shops[["Sales"]].dtypes

Sales    int64
dtype: object

In [180]:
mask = df_fruits["Price"] > 1.80

In [183]:
df_fruits

    Fruit  Price
0   apple    1.2
1  banana    1.5
2  orange    1.9

In [181]:
mask

0    False
1    False
2     True
Name: Price, dtype: bool

In [182]:
df_fruits[mask]

    Fruit  Price
2  orange    1.9

In [184]:
df_fruits[df_fruits["Price"] <= 1.50]

    Fruit  Price
0   apple    1.2
1  banana    1.5

In [185]:
df_fruits[df_fruits["Fruit"] == "apple"]

   Fruit  Price
0  apple    1.2

In [186]:
df_fruits[df_fruits["Fruit"] = "apple"]

SyntaxError: cannot assign to subscript here. Maybe you meant '==' instead of '='? (2739145097.py, line 1)

In [187]:
df_fruits[(df_fruits["Fruit"] == "apple") | (df_fruits["Fruit"] == "orange")]

    Fruit  Price
0   apple    1.2
2  orange    1.9

In [194]:
df_fruits[(df_fruits["Price"] >= 1.5) & (df_fruits["Price"] <= 1.9)]

    Fruit  Price
1  banana    1.5
2  orange    1.9

In [195]:
df_fruits["In_Stock"] = True

In [196]:
df_fruits

    Fruit  Price  In_Stock
0   apple    1.2      True
1  banana    1.5      True
2  orange    1.9      True

In [199]:
df_fruits["Quantity"] = [10, 20, 15] 
df_fruits["TotalValue"] = df_fruits["Price"] * df_fruits["Quantity"]
df_fruits

    Fruit  Price  In_Stock  Quantity  TotalValue
0   apple    1.2      True        10        12.0
1  banana    1.5      True        20        30.0
2  orange    1.9      True        15        28.5

In [200]:
df_fruits[["New_Col"]] = 5

In [201]:
df_fruits

    Fruit  Price  In_Stock  Quantity  TotalValue  New_Col
0   apple    1.2      True        10        12.0        5
1  banana    1.5      True        20        30.0        5
2  orange    1.9      True        15        28.5        5

In [212]:
df_fruits["Price"] = df_fruits["Price"] * 1.1

In [211]:
df_fruits

    Fruit     Price  In_Stock  Quantity  TotalValue  New_Col
0   apple  0.030797      True        10        12.0        5
1  banana  0.038496      True        20        30.0        5
2  orange  0.048762      True        15        28.5        5

In [214]:
del df_fruits["New_Col"]

In [215]:
df_fruits

    Fruit     Price  In_Stock  Quantity  TotalValue
0   apple  0.033877      True        10        12.0
1  banana  0.042346      True        20        30.0
2  orange  0.053638      True        15        28.5

In [218]:
df_fruits["Discounted_Price"] =  df_fruits["Price"] * 0.8

In [219]:
df_fruits

    Fruit     Price  In_Stock  Quantity  TotalValue  Discounted_Price
0   apple  0.033877      True        10        12.0          0.027101
1  banana  0.042346      True        20        30.0          0.033877
2  orange  0.053638      True        15        28.5          0.042910

In [222]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv" 
df_iris = pd.read_csv(url)

In [223]:
df_iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [224]:
df_iris.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [225]:
df_iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [226]:
df_iris["sepal_length"].max()

np.float64(7.9)

In [230]:
df_iris[((df_iris["species"] == "virginica") & (df_iris["petal_length"] > 6.0))]

     sepal_length  sepal_width  petal_length  petal_width    species
105           7.6          3.0           6.6          2.1  virginica
107           7.3          2.9           6.3          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica

In [231]:
df_iris.groupby("species")["petal_length"].mean()

species
setosa        1.462
versicolor    4.260
virginica     5.552
Name: petal_length, dtype: float64

In [232]:
df_iris["species"].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [243]:
df_iris_filter =  df_iris[df_iris["sepal_width"] > 3.0] 
df_iris_filter.groupby("species")["petal_length"].mean()

species
setosa        1.480952
versicolor    4.650000
virginica     5.717647
Name: petal_length, dtype: float64

In [246]:
df_iris_setosa = df_iris[df_iris["species"] == "setosa"]
df_iris_setosa

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [247]:
df_iris_setosa["petal_length"].sum()

np.float64(73.10000000000001)

In [250]:
# 1. Build a mapping dictionary for readable labels
translate_dict = { "setosa": "Setosa", "versicolor": "Versicolor", "virginica": "Virginica" }

In [251]:
# 2. Add the new column with .map()
df_iris["species_en"] = df_iris["species"].map(translate_dict)

In [256]:
# 3. Check the result (first 5 rows)
df_iris[["species", "species_en"]].head()

       species species_en
0       setosa     Setosa
1       setosa     Setosa
2       setosa     Setosa
3       setosa     Setosa
4       setosa     Setosa
..         ...        ...
145  virginica  Virginica
146  virginica  Virginica
147  virginica  Virginica
148  virginica  Virginica
149  virginica  Virginica

[150 rows x 2 columns]

In [258]:
df_iris[["species", "species_en"]].sample(10)

        species  species_en
7        setosa      Setosa
134   virginica   Virginica
94   versicolor  Versicolor
9        setosa      Setosa
123   virginica   Virginica
51   versicolor  Versicolor
33       setosa      Setosa
75   versicolor  Versicolor
26       setosa      Setosa
122   virginica   Virginica

In [261]:
df_iris.groupby("species")["petal_length"].mean()

species
setosa        1.462
versicolor    4.260
virginica     5.552
Name: petal_length, dtype: float64

In [262]:
all_means = df_iris.groupby("species").mean() 
all_means

TypeError: dtype 'str' does not support operation 'mean'

In [264]:
all_means = df_iris.groupby("species").mean(numeric_only = True) 
all_means

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [265]:
iris_stats = df_iris.groupby("species")["petal_length"].agg(["mean", "min", "max"]) 
iris_stats

             mean  min  max
species
setosa      1.462  1.0  1.9
versicolor  4.260  3.0  5.1
virginica   5.552  4.5  6.9

In [266]:
iris_stats = df_iris.groupby("species")["petal_length"].agg(["mean", "min", "max", "sum", "count"]) 
iris_stats

             mean  min  max    sum  count
species
setosa      1.462  1.0  1.9   73.1     50
versicolor  4.260  3.0  5.1  213.0     50
virginica   5.552  4.5  6.9  277.6     50

In [267]:
df_iris.groupby("species_en")["petal_length"].mean()

species_en
Versicolor    4.260
Virginica     5.552
Setosa        1.462
Name: petal_length, dtype: float64

In [270]:
df_iris["flower_length"] = 	df_iris["petal_length"]
df_iris.groupby(["species", "flower_length"])["petal_length"].mean()

species     flower_length
setosa      1.0              1.0
            1.1              1.1
            1.2              1.2
            1.3              1.3
            1.4              1.4
            1.5              1.5
            1.6              1.6
            1.7              1.7
            1.9              1.9
versicolor  3.0              3.0
            3.3              3.3
            3.5              3.5
            3.6              3.6
            3.7              3.7
            3.8              3.8
            3.9              3.9
            4.0              4.0
            4.1              4.1
            4.2              4.2
            4.3              4.3
            4.4              4.4
            4.5              4.5
            4.6              4.6
            4.7              4.7
            4.8              4.8
            4.9              4.9
            5.0              5.0
            5.1              5.1
virginica   4.5              4.5
            4.8              4.8
            4.9              4.9
            5.0              5.0
            5.1              5.1
            5.2              5.2
            5.3              5.3
            5.4              5.4
            5.5              5.5
            5.6              5.6
            5.7              5.7
            5.8              5.8
            5.9              5.9
            6.0              6.0
            6.1              6.1
            6.3              6.3
            6.4              6.4
            6.6              6.6
            6.7              6.7
            6.9              6.9
Name: petal_length, dtype: float64